### PR TITLE
Add ACPI Samples

### PR DESCRIPTION
**Pull request by Ab2774**
Hi
I really like your work and I tested your kext and it's absolutely amazing! 
In this PR I want to make things easier and simpler and add `_OSI` which prevents the ACPI from operating under any OS but macOS.
Also, I was so busy and forgot to add Including `ACPI Samples` feature inside the releases, can you please add it?
Thanks!

### CODE REVIEW

**Comment by hieplpvip** [comment]
I'm not very fond of adding _OSI check to every SSDT. I don't think SSDT-PNLF will cause problems for Windows. WhateverGreen's SSDT-PNLF also doesn't include _OSI check, so I think we don't need to do so.

Also, I don't want to split SSDT-PNLF into multiple versions for different platforms. Are there any specific reasons to do that (apart from setting custom _UID)?

**Comment by Ab2774** [comment]
Hi, thanks for replying.
the point of this PR is to provide a short-and-light ACPI table that serves as yours, for me personally, not a fan of using DSDT when a couple of SSDTs can do the trick, you can add both each the single SSDT-PNLFs and the general SSDT-PNLF. 
Regards

**Comment by hieplpvip** [comment]
Not sure what you mean with "using DSDT".

**Comment by Ab2774** [comment]
Hi, I meant having a couple of SSDTs is better than having DSDT

**Comment by hieplpvip** [comment]
SSDT-PNLF automatically detects the platform and inject the correct _UID. It doesn't do anything with DSDT.

**Pull request closed without merging**
